config/routes.rb
Rails.application.routes.draw do
  root :to => "homes#index"
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  devise_for :users
  resources :users do
  	resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  get "home/about" => "homes#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum:200 }
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :book
	belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books,dependent: :destroy
  validates :name, presence:true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
	user_url(resource)
end

	protected

	def configure_permitted_parameters
		added_attrs = [ :email, :name, :password, :password_confirmation ]
		devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
		devise_parameter_sanitizer.permit :account_update, keys: added_attrs
		devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
	end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
	  book = Book.find(params[:book_id])
      comment = current_user.book_comments.new(book_comment_params)
      comment.book_id = book.id
      comment.save
      redirect_to book_path(book)
	end

	def destroy
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.find_by(book_id: book.id)
		comment.destroy
		redirect_to book_path(book)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment, :user_id)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    # @books = Book.joins(:user).select("books.*, users.profile_image_id")
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @book_comment = BookComment.new
  end

  def new
  end


  def create
    @book = Book.new(book_params)
    @books = Book.all
    @user = User.find(current_user.id)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "successfully"
    else
      render "index"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    if @book.update(book_params)
    redirect_to book_path(@book), notice: "successfully"
  else
    render "edit", notice: "error"
  end
  end

  private

  def book_params
  	params.require(:book).permit(:title,:body, :user_id)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_to request.referer
    end

	def destroy
		book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_to request.referer
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def about
end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		follow = current_user.active_relationships.build(follower_id: params[:user_id])
		follow.save
		redirect_to request.referer
	end

	def destroy
		follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
		follow.destroy
		redirect_to request.referer
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
    if @user == current_user
    else
      @user = User.find(current_user.id)
      redirect_to user_path(@user.id)
    end
  end

  def new
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	redirect_to user_path(@user.id), notice: "You have updated user successfully."

  else
    render :edit
  end
  end


def follows
  user = User.find(params[:id])
  @users = user.followings
end

def followers
  user = User.find(params[:id])
  @users = user.followers
end


  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1><p class="text-center">Editing Book</p></h1>

<div class="container">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
<div class="alert alert-danger">
	<h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<h4>Title</h4>
<%= f.text_field :title, class:"btn-block" %>
<h4>Opinion</h4>
<%= f.text_area :body, class:"btn-block" %>
<%= f.submit "Update Book", class:"btn btn-primary btn-block" %>
<% end %>
<p><%= link_to "Show", book_path %> | <%= link_to "Back", books_path %></p>
</div>
</div>
<P class="text-right">CopyRight Infratop.inc</P>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<table>
			<h2> User info</h2>
			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpeg", fallback:"no_image.jpg" %>
			<hr>
			<p>name <%= @user.name %></p>
			<hr>
			<p>introduciton <%= @user.introduction %></p>
			<p>follows <%= link_to follows_user_path(@user.id) do %>
							<%= @user.followings.count %></p>
					   <% end %>
				<p>followers <%= link_to followers_user_path(@user.id) do %>
								<%= @user.followers.count %></p>
							 <% end %>
			<%= link_to edit_user_path(@user), class:"btn btn-default btn-block" do %>
			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
			<% end %>
			<h2>New book</h2>
			<%= form_for(@book) do |f| %>
			<% if @book.errors.any? %>
			<div class="alert alert-danger">
				<h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
				<ul>
					<% @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			<h4>Title</h4>
			<%= f.text_field :title, class:"btn-block" %>
			<h4>Opinion</h4>
			<%= f.text_area :body, class:"btn-block" %>
			<%= f.submit "Create Book", class:"btn btn-primary btn-block" %>
			<% end %>
		</table>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover">
				<thead>
					<tr>
						<th class="col-xs-2"></th>
						<th class="col-xs-2">Title</th>
						<th class="col-xs-2">Opinion</th>
						<th class="col-xs-1"></th>
						<th class="col-xs-2"></th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td class="col-xs-2">
								<%= link_to user_path(book.user) do %>
									<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
								<% end %>
							</td>
							<td class="col-xs-2"><%= link_to book.title, book_path(book) %></td>
							<td class="col-xs-2"><%= book.body %></td>
							<td class="col-xs-1">
								<% if book.favorited_by?(current_user) %>
    								<%= link_to book_favorites_path(book), method: :delete do %>
      									<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      									<%= book.favorites.count %> いいね
      								<% end %>
									<% else %>
    									<%= link_to book_favorites_path(book), method: :post do %>
      									<i class="fa fa-heart-o" aria-hidden="true"></i>
      									<%= book.favorites.count %> いいね
    								<% end %>
								<% end %>
							</td>
							<td class="col-xs-2">コメント数: <%= book.book_comments.count %></td>
						</tr>
					<% end %>
				</tbody>

app/views/books/show.html.erb
<%= notice %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<table>
				<h2> User info</h2>
					<%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: "jpeg", fallback:"no_image.jpg" %>
					<hr>
					<p>name <%= @book.user.name %></p>
					<hr>
					<p>introduciton <%= @book.user.introduction %></p>
					<p>follows <%= link_to follows_user_path(@book.user.id) do %>
									<%= @book.user.followings.count %></p>
						   	   <% end %>
				<p>followers <%= link_to followers_user_path(@book.user.id) do %>
								<%= @book.user.followers.count %></p>
							 <% end %>
				<% if current_user != @user %>
					<% if @book.user.followed_by?(current_user) %>
						<%= link_to "フォロー外す", user_relationships_path(@book.user.id), method: :delete %>
					<% else %>
						<%= link_to "フォローする", user_relationships_path(@book.user.id), method: :post %>
					<% end %>
				<% end %>
				<% if current_user == @user %>
					<%= link_to edit_user_path(@book.user), class:"btn btn-default btn-block" do %>
						<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
					<% end %>
				<% end %>
				<h2>New book</h2>
					<%= form_for(@books) do |f| %>
						<h4>Title</h4>
						<%= f.text_field :title, class:"btn-block" %>
						<h4>Opinion</h4>
						<%= f.text_area :body, class:"btn-block" %>
						<%= f.submit "Create Book", class:"btn btn-primary btn-block" %>
					<% end %>
			</table>
		</div>

		<div class="col-xs-9">
			<table class="table">
				<h2>Book detail</h2>
					<tr>
						<td class="col-xs-2">
							<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag @book.user, :profile_image, :fill,40, 40, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %><br>
							<%= @book.user.name %>
							<% end %>
						</td>
						<td class="col-xs-2"><%= @book.title %></td>
						<td class="col-xs-2"><%= @book.body %></td>
						<td class="col-xs-2">
							<% if @book.favorited_by?(current_user) %>
    							<%= link_to book_favorites_path(@book), method: :delete do %>
    								<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      								<%= @book.favorites.count %> いいね
      							<% end %>
								<% else %>
    								<%= link_to book_favorites_path(@book), method: :post do %>
      								<i class="fa fa-heart-o" aria-hidden="true"></i>
      								<%= @book.favorites.count %> いいね
    							<% end %>
							<% end %>
						</td>
						<td class="col-xs-2">
							コメント数: <%= @book.book_comments.count %>
						</td>
						<% if @book.user == current_user %>
						<td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success btn-xs" %></td>
						<td><%= link_to "Destroy", book_path(@book), class:"btn btn-danger btn-xs", method: :delete %></td>
						<% end %>
					</tr>
			</table>
			<table class="table">
				<% @book.book_comments.each do |book_comment| %>
					<tr>
						<td class="col-xs-2">
						<%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, format: "jpeg", fallback:"no_image.jpg", size: "50x50" %>
						</td>
						<td class="col-xs-2">
							<%= book_comment.created_at.strftime('%Y/%m/%d') %>
						</td>
						<td class="col-xs-5">
							<%= book_comment.comment %>
						</td>
						<% if book_comment.user == current_user %>
							<td><%= link_to "Destroy", book_book_comments_path(@book), class:"btn btn-danger btn-xs", method: :delete %></td>
						<% end %>
					</tr>
				<% end %>
			</table>
			<%= form_for [@book, @book_comment] do |f| %>
    				<div class="col-xs-9">
            			<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
        			</div>
    			<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true">Bookers!</span></h1>
<h4><p class="text-right">copyRight Infratop.inc</p></h4>


<div id="container">
	<div id="theTarget">
		<div class="image1"></div>
		<div class="image2"></div>
		<div class="image3"></div>
		<div class="image4"></div>
		<div class="image5"></div>
	</div>
</div>

app/views/homes/index.html.erb
<%= notice %>
<div class="container">
	<div class="row">
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
<strong>Bookers</strong> !!</h1>
<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
<b>Bookers,</b></p>
<p>you can share and exchange your opinions, and emotions</p>
<p>about various books</p>
</div>
<div class="row">
<p>
	<%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-block" %>
</p>
</div>
<div class="row">
<p>
	<%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-block" %>
</p>
</div>
<p style="text-align: right">"CopyRight Infratop.inc</p>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div class="alert alert-danger">
	<h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<span>Name</span>
<%= f.text_field :name, autofocus: true %>
<span>Image</span>
<%= f.attachment_field :profile_image %>
<span>Introduction</span>
<%= f.text_area :introduction %>
<%= f.submit "Update User" %>
<% end %>

app/views/users/followers.html.erb
<h1> follower Users</h1>

<table class="table table-hover">
	<% @users.each do |user| %>
		<tr>
			<td class="col-xs-2"><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: "jpeg", fallback:"no_image.jpg", size: "50x50" %></td>
			<td class="col-xs-2"><%= user.name %></td>
			<td class="col-xs-2">フォロー数: <%= user.followings.count %></td>
			<td class="col-xs-2">フォロワー数: <%= user.followers.count %></td>
			<td class="col-cs-2">
				<% if current_user != user %>
					<% if user.followed_by?(current_user) %>
						<%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
					<% else %>
						<%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
					<% end %>
				<% end %>
			</td>
			<td class="col-xs-1"><%= link_to "Show", user_path(user) %></td>
		</tr>
	<% end %>

app/views/users/follows.html.erb
<h1> follow Users</h1>

<table class="table table-hover">
	<% @users.each do |user| %>
		<tr>
			<td class="col-xs-2"><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: "jpeg", fallback:"no_image.jpg", size: "50x50" %></td>
			<td class="col-xs-2"><%= user.name %></td>
			<td class="col-xs-2">フォロー数: <%= user.followings.count %></td>
			<td class="col-xs-2">フォロワー数: <%= user.followers.count %></td>
			<td class="col-cs-2">
				<% if current_user != user %>
					<% if user.followed_by?(current_user) %>
						<%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
					<% else %>
						<%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
					<% end %>
				<% end %>
			</td>
			<td class="col-xs-1"><%= link_to "Show", user_path(user) %></td>
		</tr>
	<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<table>
				<h2> User info</h2>
				<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpeg", fallback:"no_image.jpg" %>
				<hr>
				<p>name <%= @user.name %></p>
				<hr>
				<p>introduciton <%= @user.introduction %></p>
				<p>follows <%= link_to follows_user_path(@user.id) do %>
								<%= @user.followings.count %></p>
						   <% end %>
				<p>followers <%= link_to followers_user_path(@user.id) do %>
								<%= @user.followers.count %></p>
							 <% end %>
				<%= link_to edit_user_path(@user), class:"btn btn-default btn-block" do %>
					<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
				<% end %>
				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<h4>Title</h4>
					<%= f.text_field :title, class:"btn-block" %>
					<h4>Opinion</h4>
					<%= f.text_area :body, class:"btn-block" %>
					<%= f.submit "Create Book", class:"btn btn-primary btn-block" %>
				<% end %>
			</table>
		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table table-hover">
				<thead>
					<tr>
						<th class="col-xs-2">image</th>
						<th class="col-xs-2">name</th>
						<th class="col-xs-2"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td class="col-xs-2"><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: "jpeg", fallback:"no_image.jpg", size: "50x50" %></td>
							<td class="col-xs-2"><%= user.name %></td>
							<td class="col-xs-2">フォロー数: <%= user.followings.count %></td>
							<td class="col-xs-2">フォロワー数: <%= user.followers.count %></td>
							<td class="col-cs-2">
								<% if current_user != user %>
						    		<% if user.followed_by?(current_user) %>
										<%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
							 		<% else %>
							 		<%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
							 		<% end %>
							 	<% end %>
							</td>
							<td class="col-xs-1"><%= link_to "Show", user_path(user) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>

app/views/users/show.html.erb
<%= notice %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<table>
			<h2> User info</h2>
			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpeg", fallback:"no_image.jpg" %>
			<hr>
			<p>name <%= @user.name %></p>
			<hr>
			<p>introduciton <%= @user.introduction %></p>
			<p>follows <%= link_to follows_user_path(@user.id) do %>
							<%= @user.followings.count %></p>
					   <% end %>
				<p>followers <%= link_to followers_user_path(@user.id) do %>
								<%= @user.followers.count %></p>
							 <% end %>
			<% if current_user != @user %>
						    		<% if @user.followed_by?(current_user) %>
										<%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
							 		<% else %>
							 		<%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
							 		<% end %>
							 		<% end %>
			<% if current_user == @user %>
			<%= link_to edit_user_path(@user), class:"btn btn-default btn-block" do %>
			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
			<% end %>
			<% end %>
			<h2>New book</h2>
			<%= form_for(@book) do |f| %>
			<h4>Title</h4>
			<%= f.text_field :title, class:"btn-block" %>
			<h4>Opinion</h4>
			<%= f.text_area :body, class:"btn-block" %>
			<%= f.submit "Create Book", class:"btn btn-primary btn-block" %>
			<% end %>
		</table>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover">
				<thead>
			<tr>
				<th class="col-xs-3"></th>
				<th class="col-xs-3">Title</th>
				<th class="col-xs-3">Opinion</th>
			</tr>
		</thead>
		<tbody>
			<% @user.books.each do |book| %>
			<tr>
				<td class="col-xs-3"><%= attachment_image_tag @user, :profile_image, :fill,50, 50, format: "jpeg", fallback: "no_image.jpg", size: "50x50" %></td>
				<td class="col-xs-3"><%= link_to(book.title, "/books/#{book.id}") %></td>
				<td class="col-xs-3"><%= book.body %></td>
			</tr>
			<% end %>
		</tbody>
		</table>
		</div>
	</div>
</div>